name: prioridadeout

on:
  workflow_dispatch:      # Permite execução manual

jobs:
  run-fiscal-script:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout do código
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚨 Rodar script de prioridadeout
        run: python main.py
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SEATALK_WEBHOOK_URL: ${{ secrets.SEATALK_WEBHOOK_URL }}
